### ISSUE TITLE
selecting colors and fonts have no effect!

### ISSUE THREAD

**Issue by treborg** [termux/termux-styling#52] opened 2019-04-10 09:39 UTC
selecting colors and fonts have no effect!

**Comment by KevinBlue18** [comment] 2019-06-13 00:57
It works for me:

Color: 3024 Dark Font: Go

**Comment by KevinBlue18** [comment] 2019-06-13 01:29
It works for me:

Color: Material Font: Ubuntu![Screenshot_20190612-194306_Termux](https://user-images.githubusercontent.com/3521694/59396257-83846180-8d4d-11e9-9629-424265146c9f.jpg)

Color: 3024 Dark Font: Go![Screenshot_20190612-195049_Termux](https://user-images.githubusercontent.com/3521694/59396258-841cf800-8d4d-11e9-80db-f8edf3d1bf6d.jpg)

**Comment by thunder-coding** [comment] 2022-06-19 11:37
I don't think anyone else can reproduce the issue. Hence closing

**Closed by thunder-coding** 2022-06-19 11:37 UTC
